"""create sold_product table

Revision ID: 287295b08203
Revises: 4dfc08bb1d42
Create Date: 2022-08-18 20:25:16.931150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '287295b08203'
down_revision = '4dfc08bb1d42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sold_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category'], ['categories.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sold_products')
    # ### end Alembic commands ###
