"""create all_orders table

Revision ID: 4f4f8d7a7913
Revises: f110b6ea1edc
Create Date: 2022-08-14 17:39:44.949825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f4f8d7a7913'
down_revision = 'f110b6ea1edc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('all_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('client_cpf', sa.String(), nullable=False),
    sa.Column('active_client', sa.Boolean(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('all_orders')
    # ### end Alembic commands ###
