"""create sold_orders table

Revision ID: 85861258aad9
Revises: 4f4f8d7a7913
Create Date: 2022-08-14 17:48:07.586357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85861258aad9'
down_revision = '4f4f8d7a7913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sold_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sold_product_id', sa.Integer(), nullable=True),
    sa.Column('all_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['all_order_id'], ['all_orders.id'], ),
    sa.ForeignKeyConstraint(['sold_product_id'], ['sold_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sold_orders')
    # ### end Alembic commands ###
