"""create isAdm column in client table

Revision ID: 9cda32ef1a56
Revises: ebbb110c597d
Create Date: 2022-08-30 19:04:15.293261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cda32ef1a56'
down_revision = 'ebbb110c597d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('isAdm', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'isAdm')
    # ### end Alembic commands ###
