"""create sold_order table

Revision ID: d1e5f5215d48
Revises: 7bf7147b0234
Create Date: 2022-08-18 20:25:49.384942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1e5f5215d48'
down_revision = '7bf7147b0234'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sold_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sold_product_id', sa.Integer(), nullable=True),
    sa.Column('all_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['all_order_id'], ['all_orders.id'], ),
    sa.ForeignKeyConstraint(['sold_product_id'], ['sold_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sold_orders')
    # ### end Alembic commands ###
