class WrongKeys(Exception):
    ...

class InvalidValues(Exception):
    ...

class CpfInvalid(Exception):
    ...

class ClientNotFound(Exception):
    ...

class ProductNotFound(Exception):
    ...

class UndefinedQuantity(Exception):
    ...

class DuplicateProduct(Exception):
    ...

class UnavailableProduct(Exception):
    ...

class InvalidCredentials(Exception):
    ...

class MissingToken(Exception):
    ...

class AdmRequired(Exception):
    ...