"""create all_order table

Revision ID: 0468d9a2d9f3
Revises: 22ad44f31473
Create Date: 2022-08-22 23:00:35.108706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0468d9a2d9f3'
down_revision = '22ad44f31473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('all_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('client_cpf', sa.String(), nullable=False),
    sa.Column('active_client', sa.Boolean(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('all_orders')
    # ### end Alembic commands ###
