"""insert product_amount column in sold_order table

Revision ID: 988066a2da9a
Revises: 95e1873b88bf
Create Date: 2022-08-23 19:47:19.316077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988066a2da9a'
down_revision = '95e1873b88bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sold_orders', sa.Column('product_amount', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sold_orders', 'product_amount')
    # ### end Alembic commands ###
